### ISSUE TITLE
Feature request: Crane Inward Projecting Pipe Entrance

### ISSUE THREAD

**Issue by MTkeg** [CalebBell/fluids#20]
Thanks for pulling together this awesome tool!  Is it possible to implement another method in entrance_distance for Crane or maybe create an entrance_distance_Crane function?  The Crane Handbook indicates inward projections have a K = 0.78.

Thanks,

MT

**Comment by CalebBell** [comment]
Hi MT,
Thank you for the compliment. 
Adding the Crane value is not a bad idea. I'm trying to avoid adding too many functions, so I'm trying to add new fitting functions into existing ones where the method can be specified. I've added it to "entrance_distance" under the "Crane" method, and made the pipe wall thickness optional.
You can install fluids from git to get the feature now, or wait to the next release.
Cheers,
Caleb

**Comment by MTkeg** [comment]
Thanks!  I truly understand where you are coming from with respect to
adding too many new functions!

I was wondering if you could provide some assistance, I tried to use git to
get the feature now but I am not sure if I am doing it correctly.
Unfortunately, I am using a Windows Machine but I do have git installed.
What steps do I need to take to get the new feature up and running?  I
originally installed fluids via the 'pip install fluids' command.

As a side bar, I use the Crane handbook heavily and was wondering if you
had functions for Crane's "standard" bends embedded anywhere in the
program.  I looked but didn't seem to find it.

Thanks again for everything!

MT
