### ISSUE TITLE
Add setuptools support

### ISSUE THREAD

**Issue by kkremitzki** [CalebBell/fluids#21]
It would be nice if setuptools was supported so its features beyond distutils could be used, e.g. building eggs. I'd be willing to implement this, but I thought I might create an issue first to make sure there's interest in merging it.

**Comment by CalebBell** [comment]
Hi Kurt!

Thank you very much for the generous offer! I know it would have been better to use setuptools to package fluids. As you know, packaging can be very frustrating - and once I had distutils working, I moved on and haven't thought about it in almost three years. I already have two setuptools keywords: extras_require and install_requires which aren't doing anything right now.

I would absolutely welcome any help. 

Congratulations on your new job as well!
Sincerely,
Caleb
