### ISSUE TITLE
Feature request: ndarray support for friction factor

### ISSUE THREAD

**Issue by Hagobert** [CalebBell/fluids#22]
Hi. I am working with a lot of arrays for design studies and would love to use fluids. My first application case uses your friction_factor function. Unfortunately it seems that I can only calculate one value at a time. As I would like to avoid looping over my entire array it would be great if you could implement ndarray functionality to the friction_factor module.

Cheers

**Comment by CalebBell** [comment]
Hi Hagobert,
ndarray support is offered through the fluids.vectorized module; so instead of using "from fluids import friction_factor" use "from fluids.vectorized import friction_factor" , as covered in the [tutorial](https://fluids.readthedocs.io/tutorial.html#design-philosophy).

Sincerely,
Caleb

**Comment by Hagobert** [comment]
My bad thank you
