### ISSUE TITLE
Typo in Haaland equation

### ISSUE THREAD

**Issue by hagen-kellermann** [CalebBell/fluids#23]
Hi there

I just stumbled across what I think is a misstake in your equation for the explicit Haaland expression in friction_factor. I do have both sources that you cite and Haaland himself states -1.8 to be the constant before the log. However in Winnings work the formulation is given with a -3.6 factor. Winning directly cites Haaland so I believe it might be a typo in Winnings work. 

Cheers

**Comment by CalebBell** [comment]
Hi again Hagobert,

The difference in the coefficient comes from whether or not the equation is being written to calculate the Darcy or the Fanning friction factor. The one in the documentation is for the Fanning friction factor (ff); the form with 3.6 is for Darcy's form (fd). In the code, a multiplier of 4 is used after the calculation is done with the 1.8 coefficient to convert it to Darcy's form.

Cheers,
Caleb
