### ISSUE TITLE
Bubbling flow in reactors

### ISSUE THREAD

**Issue by alexchandel** [CalebBell/fluids#33]
A common situation involves a vertical liquid-phase reactor / tower, where gas bubbles are evolving (or being consumed) throughout the tower at some exogenous rate "rate(height, T, P, x̄ )" and ascending at a different rate from the liquid's flowrate (possibly passing through mixing trays), to form a controlled gas pocket of variable volume at the top of the tower.  This may be (but is not necessarily) a fluidized bed reactor.

While fluids has [some two-phase functions](https://fluids.readthedocs.io/fluids.two_phase.html), it lacks functions for the prediction of bubble diameters, evolution of bubble diameters, & ascension rates.  Some solved problems for vertical and horizontal two-phase flow would be welcome as well.

**Comment by CalebBell** [comment]
Hi Alex,
Of course the functions you propose would be welcome in fluids. I am a little farmilar with the correlations but it is not presently on my development agenda. A fair deal of code for dealing wtih particle size distributions and single particles in motion already exist, in [fluids.drag](https://fluids.readthedocs.io/fluids.drag.html) and [fluids.particle_size_distribution](https://fluids.readthedocs.io/fluids.particle_size_distribution.html).
If you have need for these functions, would you like to take a stab at adding some functions?
Sincerely,
Caleb

**Comment by alexchandel** [comment]
I can attempt some next time the need arises.

**Comment by CalebBell** [comment]
Closing this as stale.
