### ISSUE TITLE
docs, unit of measurement for f and k in fluids.geometry.TANK

### ISSUE THREAD

**Issue by anthracitegrey** [CalebBell/fluids#34]
From [https://fluids.readthedocs.io/fluids.geometry.html#module-fluids.geometry]():

sideA_f : Dish-radius parameter for side A; *fD* = dish radius **[1/m]**

Shouldn't *f* and *k* be dimensionless? Then *fD* is in [m], just like *D*.

**Comment by CalebBell** [comment]
Good catch! I think I confused the units while working with the Honeywell whitepaper: https://www.honeywellprocess.com/library/marketing/whitepapers/WP-VesselsWithDishedHeads-UniSimDesign.pdf
Easy enough to fix - and more importantly, to check. We can use `pint` with the existing functions (and only one change) to check the unit needs to be different.

```
def V_vertical_torispherical(D, f, k, h):
    alpha = asin((1-2*k)/(2*(f-k)))
    a1 = f*D*(1 - cos(alpha))
    a2 = k*D*cos(alpha)
    D1 = 2*f*D*sin(alpha)
    s = (k*D*sin(alpha))**2
    t = 2*a2
    u = h - f*D*(1 - cos(alpha))

    if 0 <= h.magnitude <= a1.magnitude:
        Vf = pi*h**2/4*(2*a1 + D1**2/2/a1 - 4*h/3)
    elif a1.magnitude < h.magnitude <= (a1 + a2).magnitude:
        Vf = (pi/4*(2*a1**3/3 + a1*D1**2/2.) + pi*u*((D/2. - k*D)**2 + s)
        + pi*t*u**2/2. - pi*u**3/3. + pi*D*(1 - 2*k)*((2*u-t)/4.*(s + t*u
        - u**2)**0.5 + t*s**0.5/4. + k**2*D**2/2*(acos((t-2*u)/(2*k*D))-alpha)))
    else:
        Vf = pi/4*(2*a1**3/3. + a1*D1**2/2.) + pi*t/2.*((D/2 - k*D)**2
        + s) + pi*t**3/12. + pi*D*(1 - 2*k)*(t*s**0.5/4
        + k**2*D**2/2*asin(cos(alpha))) + pi*D**2/4*(h - (a1 + a2))
    return Vf


V_vertical_torispherical(D=132.*u.m, f=1.0*u.dimensionless, k=0.06*u.dimensionless, h=24*u.m)

```
The above works, but` V_vertical_torispherical(D=132.*u.m, f=1.0/u.m, k=0.06/u.m, h=24*u.m)` does not (and the same for other functions).

I have pushed out an 0.1.78 release with the fix.

Cheers,
Caleb
