### ISSUE TITLE
How to get the accurate average compression factor in the empirical formula

### ISSUE THREAD

**Issue by CatNofishing** [CalebBell/fluids#35]
I noticed that the average compression factor defaults to 1, but this is not accurate. Is there any other way to auto calculate the average compression factor。

![image](https://user-images.githubusercontent.com/33288114/94364541-a1b9d080-00fc-11eb-8973-f8efed3c19a0.png)

**Comment by CalebBell** [comment]
Hi Cat,
It is left up to the user to calculate Z. You can allow Z to change by performing either numerical integration or segmenting the pipe into smaller sections of pipe.
Sincerely,
Caleb

**Comment by CatNofishing** [comment]
Thank you for your reply, it may be a bit difficult for me. The average compression factor is related to the average pressure, and the average pressure depends on the starting and ending pressures. If I only know the flow and starting pressure......,I don not know how to do

**Comment by CalebBell** [comment]
Hi Cat,
The documentation includes a sample calculation here: https://fluids.readthedocs.io/Examples/Crane%20TP%20410%20Solved%20Problems/7.22%20Compressible%20Fluids%20at%20Subsonic%20Velocity.html
Sincerely,
Caleb
