### ISSUE TITLE
model name bug  in  <two_phase.py>

### ISSUE THREAD

**Issue by hohiroki** [CalebBell/fluids#40]
line 2507: the model name "Beggs-Brill" might be revised as "Beggs_Brill"

**Comment by CalebBell** [comment]
Hi hohiroki,
I agknoeledge the inconsistency in that some of the options use a understore and this one use dash. I try to avoid breaking backwards compatibility pretty hard, so I'm afraid this will stay as it is as there are people using those code.
Cheers,
Caleb
