### ISSUE TITLE
Particle Size Distribution Tutorial

### ISSUE THREAD

**Issue by mckel-9** [CalebBell/fluids#48]
Shouldn't be the function `mean_size_ISO` be used instead of `mean_size`  in the examples given in the tutorial for particle size distributions?

In the following lines, the SMD would otherwise be `psd.mean_size(3,2)` and not `psd.mean_size(1,2)`.

https://github.com/CalebBell/fluids/blob/3ab91928331f536d37376ad75939780398d1f0c5/docs/tutorial.rst#L1479-L1492

**Comment by CalebBell** [comment]
Hey, thanks for the catch. I updated the results and the indexes.
