### ISSUE TITLE
LGTM reports keyword argument `ags` is not a supported parameter name of function `quad_adaptive`

### ISSUE THREAD

**Issue by luzpaz** [CalebBell/fluids#50]
https://github.com/CalebBell/fluids/blob/b9907e47e0b088636921d28f0ccffbaf5d74227d/fluids/numerics/__init__.py#L4384

![Screenshot_20220802_115006](https://user-images.githubusercontent.com/4140247/182417590-129d50c0-5658-451b-85b7-bcec8f395107.png)

Ref: https://lgtm.com/projects/g/CalebBell/fluids/?mode=tree&ruleFocus=900075

**Comment by CalebBell** [comment]
Thanks! I guess that part of the code wasn't used anywhere or I would have found it, but this will make using this easier in the future!

Caleb
