### ISSUE TITLE
Error in contextual help: Reynolds function

### ISSUE THREAD

**Issue by benardt** [CalebBell/fluids#51]
For Reynolds calculation function, I think there is a mistake between **kinematic** and **dynamic** viscosity.

see: https://en.wikipedia.org/wiki/Reynolds_number

-------------------------------------------------------------
Reynolds(V, D, rho=None, mu=None, nu=None)

Calculates Reynolds number or Re for a fluid with the given
properties for the specified velocity and diameter.

Inputs either of any of the following sets:

* V, D, density rho and **kinematic viscosity mu**
* V, D, and **dynamic viscosity nu**
-------------------------------------------------------------

**Comment by CalebBell** [comment]
Good catch! 
This is now fixed in fluids 1.0.22.
