### ISSUE TITLE
Calculation of G in K_branch_diverging_Crane

### ISSUE THREAD

**Issue by Flixie420** [CalebBell/fluids#63]
I think that there may be an issue in the calculation of G, when calculating the K-factor for the branch of a diverging Tee.

G is determined according to the following pseudocode:
```
if angle < 75:
    if beta2 <= 0.35:
        if` Q_ratio <= 0.4:
            G = 1.1 - 0.7*Q_ratio
        else:
            G = 0.85
    else:
        if Q_ratio <= 0.6:
            G = 1.0 - 0.6*Q_ratio
        else:
            G = 0.6
else:
    if beta2 <= 2/3.:
        G = 1
    else:
        G = 1 + 0.3*Q_ratio*Q_ratio
```

The "angle<75" condition isn't mentioned in crane (to my knowledge), so G should only determined by the following part of the code:
```
if beta2 <= 0.35:
      if Q_ratio <= 0.4:
          G = 1.1 - 0.7*Q_ratio
      else:
          G = 0.85
  else:
      if Q_ratio <= 0.6:
          G = 1.0 - 0.6*Q_ratio
      else:
          G = 0.6
```

Could you please tell me where the angle<75 condition came from?

**Comment by CalebBell** [comment]
Hi Flixie420,
I agree that Crane TP 410M doesn't list a specific use of 75 degrees. Instead, they provide recommendations for 90 degree tees and for 0-60 degree tees. To cover the gap, I decided to split the difference between the 60 and 90 degree behavior at 75 degrees. I didn't remember exactly what I did here for a little while so even though I explicitly included the pseudocode to show what I chose, I will add a further comment explaining this choice. You can see the tables for these cases in the errata, tables 2-3 and 2-4. https://web.archive.org/web/20200125134233/http://flowoffluids.com/media/1002/metric-errata-document-nov2012.pdf
Sincerely,
Caleb
